name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      env:
        AWS_REGION: 'ap-southeast-1'
        ECR_REGISTRY: '533267050904.dkr.ecr.ap-southeast-1.amazonaws.com'
        ECR_REPOSITORY: 'bitcoin-backend'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

    - name: Build Docker Image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

    - name: Push Image to Amazon ECR
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl rollout restart deployment/runebeta-testnet
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

