name: Deployment
permissions:
  id-token: write 
  contents: read  
on:
  push:
    branches: [ "develop", "main" ]
  workflow_dispatch:
  
jobs:
  develop:
    if: github.ref_name == 'develop' || github.event_name == 'workflow_dispatch' 
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: build
      run: |
        docker build . -f Dockerfile -t ${{ github.event.repository.name }}
    - name: stop container
      run: docker stop ${{ github.event.repository.name }} || echo 
    - name: running
      env:
        SUPER_SECRET: ${{ secrets.ENV_FILE }}
      run: |
        echo "$SUPER_SECRET" > .env
        docker run --rm -p 3000:3000 \
        --network=host --name ${{ github.event.repository.name }} --env-file .env -d ${{ github.event.repository.name }}
      
    - name: health-check
      run: |
        for i in {1..60}
        do
            curl localhost:3000 -I -s | grep "200 OK"
            [ $status -eq 0 ] && exit 0 || sleep 5;
        done
        exit 2