name: Deployment runebeta
permissions:
  id-token: write 
  contents: read  
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  release:
    if: github.ref_name == 'master' || github.event_name == 'workflow_dispatch' 
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Build docker image
      run: |
        docker build . -f Dockerfile -t ${{ github.event.repository.name }}
    - name: stop container
      run: docker stop ${{ github.event.repository.name }} || echo 
    - name: Running container
      env:
        SUPER_SECRET: ${{ secrets.ENV_FILE }}
      run: |
        echo "$SUPER_SECRET" > .env
        docker run --rm -p 3000:3000 \
        --network=host --name ${{ github.event.repository.name }} --env-file .env -d ${{ github.event.repository.name }}
      
    - name: Health-check
      run: sleep 60 && curl localhost:3000